repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
        files: .
      - id: end-of-file-fixer
        files: .
      - id: trailing-whitespace
        files: .

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        files: .py
