# Generated by Django 4.2.1 on 2024-02-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('link_to_bgg', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=70)),
                ('nickname', models.CharField(max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('boardgames', models.ManyToManyField(related_name='users_users', to='user.boardgames')),
                ('friends', models.ManyToManyField(related_name='user_friends', to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='boardgames',
            name='users',
            field=models.ManyToManyField(related_name='boardgames_owners', to='user.user'),
        ),
    ]
