# Generated by Django 4.2.1 on 2024-02-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgames',
            name='users',
        ),
    ]
