# Generated by Django 4.2.1 on 2024-02-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_boardgames_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='boardgames',
            field=models.ManyToManyField(blank=True, related_name='users_users', to='user.boardgames'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='user_friends', to='user.user'),
        ),
    ]
